dest = "/"

[prompts]
nvidia                 = { type = "bool", question = "NVIDIA GPU (modules, modprobe)" }
tpm2_unlock            = { type = "bool", question = "TPM2 LUKS auto-unlock" }
laptop                 = { type = "bool", question = "Laptop (battery tmpfiles)" }
block_nextcloud_user_c = { type = "bool", question = "Block nextcloud for user_c" }
block_network_user_c   = { type = "bool", question = "Block network for user_c" }
