[options]
HoldPkg     = pacman glibc
Architecture = auto

Color
CheckSpace
ParallelDownloads = 5
DownloadUser = alpm

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[custom]
SigLevel = Optional TrustAll
Server = file:///var/cache/pacman/custom

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
